apiVersion : apps/v1
kind: Deployment
metadata:
  name: wizecommerceodata-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
        app: wizecommerceodata
  template:
    metadata:
      labels:
        app: wizecommerceodata 
    spec:
      containers:
        - name: wizecommerceodata 
          image: brandonkorouscontainers.azurecr.io/wizecommerceodata
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "Auth0_Authority"
            valueFrom:
              secretKeyRef: 
                name: auth0-commerce-secrets
                key: Auth0_Authority
          - name: "Auth0_ClientId"
            valueFrom:
              secretKeyRef: 
                name: auth0-commerce-secrets
                key: Auth0_ClientId
          - name: "Auth0_ClientSecret"
            valueFrom:
              secretKeyRef: 
                name: auth0-commerce-secrets
                key: Auth0_ClientSecret
          - name: "Auth0_Audience"
            valueFrom:
              secretKeyRef: 
                name: auth0-commerce-secrets
                key: Auth0_Audience
          - name: "JwtAuthentication_ValidAudience"
            valueFrom:
              secretKeyRef: 
                name: authentication-commerce-secrets
                key: JwtAuthentication_ValidAudience
          - name: "JwtAuthentication_ValidIssuer"
            valueFrom:
              secretKeyRef: 
                name: authentication-commerce-secrets
                key: JwtAuthentication_ValidIssuer
          - name: "ConnectionStrings_WizeWorksContext"
            valueFrom:
              secretKeyRef: 
                name: connectionstrings-commerce-secrets
                key: ConnectionStrings_WizeWorksContext
          - name: "ConnectionStrings_TenantsContext"
            valueFrom:
              secretKeyRef: 
                name: connectionstrings-commerce-secrets
                key: ConnectionStrings_TenantsContext
          - name: "ConnectionStrings_ApplicationInsights"
            valueFrom:
              secretKeyRef: 
                name: connectionstrings-commerce-secrets
                key: ConnectionStrings_ApplicationInsights
          - name: "ConnectionStrings_Sentry"
            valueFrom:
              secretKeyRef: 
                name: connectionstrings-commerce-secrets
                key: ConnectionStrings_Sentry